[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
extra_scripts =
  post:scripts/fix_uploadfs.py

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++20
  -O2
  -Wall
  -Wextra
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_INCLUDE_SIMPLE
  -I .

lib_deps =
  lvgl/lvgl@9.3.0
  lovyan03/LovyanGFX@1.2.24

upload_speed = 921600
upload_protocol = esptool

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
